esphome:
  name: custom-senor
  includes:
    - my_custom_sensor.h
esp8266:
  board: d1
 
# Enable logging
logger:
 
# Enable Home Assistant API
api:
  encryption:
    key: "3ETekMVZwaS8h0O5itA3P8ZzaSZnasIIYMZQkwlMe4o="
 
ota:
  password: "4c0bbcc77dfad762f9c5fa64fe8fe18d"
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Custom-Senor Fallback Hotspot"
    password: "knR4cbONDdE4"
sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new MyCustomSensor();
      App.register_component(my_sensor);
      return {my_sensor->result};
 
    sensors:
      name: "My Custom Sensor"
      unit_of_measurement: ugm/m^3
      accuracy_decimals: 1
 
  - platform: dht
    pin: D8
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 30s
 
binary_sensor:
  - platform: gpio
    pin: D10
    name: TTP223
    on_press:
      then:
        - switch.toggle: led_switch
 
switch:
  - platform: gpio
    pin: D5
    name: led_switch
    id: led_switch
   
captive_portal:
   
 

